"use client";

/** Consent-driven GPS trip guidance with selectable alighting stop and get-off warning. */

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { apiClient, Node, Route, RouteGeometry } from "@/lib/api-client";
import { LiveTripMap } from "@/components/live-trip-map";
import { distanceToPolylineMeters, isApproximateFix, isOffRoute } from "@/lib/geo";

type Position = { lat: number; long: number; accuracy: number };
function distanceMeters(a: { lat: number; long: number }, b: { lat: number; long: number }) { const radius = 6371000; const toRad = (value: number) => value * Math.PI / 180; const dLat = toRad(b.lat - a.lat); const dLong = toRad(b.long - a.long); const left = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLong / 2) ** 2; return 2 * radius * Math.asin(Math.sqrt(left)); }

export function LiveTrip({ routeId }: { routeId: number }) {
  const [route, setRoute] = useState<Route | null>(null); const [stops, setStops] = useState<Node[]>([]); const [geometry, setGeometry] = useState<RouteGeometry | null>(null); const [position, setPosition] = useState<Position | null>(null); const [targetId, setTargetId] = useState(0); const [tracking, setTracking] = useState(false); const [error, setError] = useState(""); const watchRef = useRef<number | null>(null);
  useEffect(() => { let cancelled = false; Promise.all([apiClient.routes.get(routeId), apiClient.nodes.list(routeId), apiClient.routes.geometry(routeId)]).then(([nextRoute, nextStops, nextGeometry]) => { if (!cancelled) { const ordered = [...nextStops].sort((a,b) => a.orderNum - b.orderNum); setRoute(nextRoute); setStops(ordered); setGeometry(nextGeometry); setTargetId(ordered.at(-1)?.id ?? 0); } }).catch((requestError: unknown) => { if (!cancelled) setError(requestError instanceof Error ? requestError.message : "Could not load this route"); }); return () => { cancelled = true; if (watchRef.current !== null) navigator.geolocation.clearWatch(watchRef.current); }; }, [routeId]);
  function startTracking() { if (!navigator.geolocation) { setError("Live location is not available in this browser."); return; } setError(""); setTracking(true); watchRef.current = navigator.geolocation.watchPosition((reading) => setPosition({ lat: reading.coords.latitude, long: reading.coords.longitude, accuracy: reading.coords.accuracy }), (locationError) => { setTracking(false); setError(locationError.code === 1 ? "Location permission was not granted. You can still inspect the route." : "Your location could not be updated."); }, { enableHighAccuracy: true, maximumAge: 5000, timeout: 15000 }); }
  function stopTracking() { if (watchRef.current !== null) navigator.geolocation.clearWatch(watchRef.current); watchRef.current = null; setTracking(false); }
  const target = stops.find((stop) => stop.id === targetId) ?? null;
  const targetDistance = position && target ? Math.round(distanceMeters(position, target)) : null;
  const nearestIndex = useMemo(() => { if (!position || !stops.length) return -1; return stops.reduce((best, stop, index) => distanceMeters(position, stop) < distanceMeters(position, stops[best]) ? index : best, 0); }, [position, stops]);
  const targetIndex = stops.findIndex((stop) => stop.id === targetId); const stopsAway = nearestIndex >= 0 && targetIndex >= 0 ? Math.max(0, targetIndex - nearestIndex) : null; const getReady = targetDistance !== null && targetDistance <= 450;
  const routeOffset = position && geometry?.coordinates?.length ? distanceToPolylineMeters(position, geometry.coordinates as [number, number][]) : null;
  const offRoute = position && routeOffset !== null && Number.isFinite(routeOffset) ? isOffRoute(routeOffset, position.accuracy) : false;
  const approximate = position ? isApproximateFix(position.accuracy) : false;
  return <div className="live-trip-page"><header className="live-trip-header"><div><Link href="/routes">← Back to routes</Link><span className="page-eyebrow">Live trip guidance</span><h1>{route?.name ?? "Loading route…"}</h1><p>Choose where you want to get off, then start GPS tracking. Keep checking the road and confirm with the driver.</p></div><div className={`live-status ${tracking ? "active" : ""}`}><i/><span>{tracking ? "GPS active" : "GPS off"}</span></div></header>{error && <div className="alert alert-error">{error}</div>}{offRoute && routeOffset !== null && <div className="off-route-card" role="alert"><strong>You may be off this route.</strong><span>Your location is about {Math.round(routeOffset)} m from the mapped road. Drivers divert and stops move, so ask the driver and check your stop before relying on this screen.</span></div>}{approximate && !offRoute && <div className="off-route-card soft" role="status"><strong>Your location is approximate right now.</strong><span>GPS is only accurate to about {Math.round(position?.accuracy ?? 0)} m, so distances and warnings may be late. Watch the road.</span></div>}<section className="live-trip-workspace"><LiveTripMap stops={stops} geometry={geometry} position={position} targetId={targetId}/><aside className="live-trip-panel"><label>Where are you getting off?<select value={targetId} onChange={(event) => setTargetId(Number(event.target.value))}>{stops.map((stop, index) => <option key={stop.id} value={stop.id}>{index + 1}. {stop.name}</option>)}</select></label><div className={`get-off-card ${getReady ? "urgent" : ""}`}><span>{getReady ? "Get ready" : tracking ? "Next check" : "Before you start"}</span><h2>{getReady ? "Your stop is close." : target?.name ?? "Choose a stop"}</h2><p>{targetDistance === null ? "Start tracking when you board. Your location is only used on this device." : `${targetDistance < 1000 ? `${targetDistance} m` : `${(targetDistance / 1000).toFixed(1)} km`} away${stopsAway !== null ? ` · about ${stopsAway} mapped stops` : ""}`}</p></div>{tracking ? <button className="btn btn-secondary btn-full" onClick={stopTracking}>Stop live tracking</button> : <button className="btn btn-dark btn-full" onClick={startTracking}>Use my live location →</button>}<div className="live-privacy"><strong>Location stays in your browser</strong><p>The API receives no live GPS trail. Guidance is distance-based and cannot detect diversions, moving stops, or the vehicle you boarded.</p></div><ol className="live-stop-list">{stops.map((stop, index) => <li className={stop.id === targetId ? "target" : index < nearestIndex ? "passed" : ""} key={stop.id}><span>{String(index + 1).padStart(2,"0")}</span><strong>{stop.name}</strong></li>)}</ol></aside></section></div>;
}
